#####
#file: Makefile
#author: Jan Wrona
#email: <xwrona00@stud.fit.vutbr.cz>
#date: 24.4.2015
#project: Mesh Multiplication, PRL
#####

NAME=mm

latex: $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).{aux,log,out,toc,bbl,blg}
