#####
#file: makefile
#author: Jan Wrona
#email: <xwrona00@stud.fit.vutbr.cz>
#date: 21.3.2015
#project: Implementace algoritmu "Pipeline merge sort", PRL
#####

NAME=pms

latex: $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).{aux,log,out,toc,bbl,blg}
